(custom-set-variables
 '(column-number-mode t)
 '(font-lock-maximum-decoration t)
 '(font-lock-maximum-size nil)
 '(line-number-mode t)
 '(load-home-init-file t t)
 '(paren-mode (quote paren) nil (paren))
 '(ps-print-color-p nil t)
 '(query-user-mail-address nil)
 '(toolbar-visible-p nil)
 '(zmacs-regions t))
(custom-set-faces
 '(custom-comment-face ((((class grayscale color) (background light)) (:foreground "white" :background "gray20"))))
 '(custom-comment-tag-face ((((class color) (background light)) (:foreground "blue"))))
 '(custom-set-face ((((class color)) (:foreground "lightblue" :background "gray20"))))
 '(ediff-current-diff-face-A ((((type tty)) (:foreground "black" :background "yellow"))))
 '(ediff-current-diff-face-B ((((type tty)) (:foreground "black" :background "yellow" :weight bold)) (((class color)) (:foreground "DarkOrchid" :background "Yellow")) (t (:inverse-video t))))
 '(ediff-fine-diff-face-A ((((type tty)) (:foreground "white" :background "blue" :weight bold)) (((class color)) (:foreground "Navy" :background "blue")) (t (:underline t :stipple "gray"))))
 '(ediff-fine-diff-face-B ((((type tty)) (:foreground "white" :background "blue"))))
 '(font-lock-builtin-face ((((class color) (background dark)) (:foreground "Purple"))))
 '(font-lock-comment-face ((nil (:foreground "blue"))))
 '(font-lock-doc-string-face ((((class color) (background dark)) (:foreground "green"))))
 '(font-lock-function-name-face ((((class color) (background dark)) (:foreground "red"))))
 '(font-lock-keyword-face ((((class color) (background dark)) (:foreground "white"))))
 '(font-lock-string-face ((((class color) (background dark)) (:foreground "green"))))
 '(font-lock-variable-name-face ((((class color) (background dark)) (:foreground "cyan"))))
 '(gui-button-face ((t (:foreground "white" :background "gray20" :inverse-video t))) t)
 '(highlight ((t (:foreground "black" :background "yellow"))) t)
 '(isearch ((t (:foreground "black" :background "yellow"))) t)
 '(list-mode-item-selected ((t (:background "#555555"))) t)
 '(modeline ((t (:foreground "white" :background "black"))) t)
 '(modeline-buffer-id ((t (:foreground "lightblue" :background "gray20"))) t)
 '(modeline-mousable ((t (:foreground "red" :background "gray20"))) t)
 '(paren-match ((t (:foreground "red" :background "darkseagreen2"))) t)
 '(primary-selection ((t (:foreground "black" :background "yellow"))) t)
 '(secondary-selection ((t (:background "#555555"))) t)
 '(widget-field-face ((((class grayscale color) (background light)) (:background "gray20"))))
 '(zmacs-region ((t (:foreground "black" :background "yellow"))) t))
